
name = "aurora-bank"
main = "./dist/index.js"  # Explicit entry point
compatibility_date = "2025-05-08"  # Updated to current date
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
upload_dir = "dist"  # Replaces [site] section for Pages

# For static assets (CSS, images, etc.)
[[rules]]
globs = ["**/*.css", "**/*.png", "**/*.jpg"]
type = "ESModule"
