
name = "aurora-bank"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./dist"

# Explicitly define assets configuration
[build]
command = "npm run build"

# Ensure proper asset handling
[assets]
directory = "./dist"
